### ISSUE TITLE
[Bug] jumpserver-jms-celery一直在重启

### ISSUE THREAD

**Issue by jeessy2** [jumpserver/helm#8]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
Liveness probe failed: OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "./jms status task | grep stopped && exit 1 || exit 0": stat ./jms status task | grep stopped && exit 1 || exit 0: no such file or directory: unknown

**Bug 重现步骤(有截图更好)**
1.  ![截屏2021-08-18 上午10 16 10](https://user-images.githubusercontent.com/6205259/129825921-544df534-3baa-40ea-a6cc-e6dce411f3ad.png)
2. 
3.

**Comment by jeessy2** [comment]
deployment-celery.yaml修改后正常
```
          livenessProbe:
            exec:
              command:
                - cat
                - /opt/jumpserver/tmp/celery_default.pid
```
